trigger: none
pool: My_agent_pool

stages:
  - stage: terraforminit
    jobs:
      - job: init
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/'
            backendServiceArm: 'ispyarkokyanaamdo-manoj'
            backendAzureRmResourceGroupName: 'kssk'
            backendAzureRmStorageAccountName: 'stg'
            backendAzureRmContainerName: 'ctr'
            backendAzureRmKey: 'dev.tfstate'

  - stage: Terraformplan
    jobs:
      - job: plan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/'
            backendServiceArm: 'ispyarkokyanaamdo-manoj'
            backendAzureRmResourceGroupName: 'rgs'
            backendAzureRmStorageAccountName: 'stg'
            backendAzureRmContainerName: 'cont'
            backendAzureRmKey: 'dev.terraform.tfvars'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/'
            environmentServiceNameAzureRM: 'ispyarkokyanaamdo-manoj'
      